# Generated by Django 2.2 on 2021-11-27 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211126_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(choices=[('UNN', 'UNN'), ('UNEC', 'UNEC')], default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
