# Generated by Django 2.2.2 on 2022-01-13 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiring_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 20, 21, 31, 56, 368712)),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, to='main.ProductTag'),
        ),
    ]
