# Generated by Django 2.2.2 on 2022-01-15 03:45

import datetime
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220113_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'max_length': '11 Numbers required.'}, help_text='11 Nigeria Phone Numbers.', max_length=11, validators=[main.models.numeric_validator], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiring_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 4, 45, 19, 90537)),
        ),
    ]
