# Generated by Django 2.2.2 on 2022-01-17 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220115_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiring_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 12, 15, 12, 307740)),
        ),
    ]
