# Generated by Django 2.2.2 on 2022-01-18 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220117_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiring_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 21, 0, 11, 762165)),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
